proxy:
  build: .
  links:
    - backend
    - backend-2
  environment:
    BACKEND: http://backend:80/ http://backend-2:80
  ports:
    - "80"
backend-2:
  extends:
    service: backend
backend:
  image: wouterd/go-hello-web